[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "clip-comparador-v2"

[service.variables]
FLASK_ENV = "production"
FLASK_DEBUG = "False"
PYTHONPATH = "/app"
